name: Auto Label PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-external:
    runs-on: ubuntu-latest
    outputs:
      EXTERNAL: ${{ steps.check-external.outputs.EXTERNAL }}
    steps:
    - name: Install deps
      run: |
        sudo apt update && sudo apt install -y jq
    - name: Get org members
      id: fetch-members
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        members=$(gh api \
          -H "Accept: application/vnd.github+json" \
          "/orgs/supabase/members?per_page=100" | jq -r '.[].login' | tr '\n' ' ')
        echo "members=${members}" >> $GITHUB_OUTPUT
    - name: Check if external contribution
      id: check-external
      run: |
        PR_OPENER="${{ github.event.pull_request.user.login }}"
        MEMBERS="${{ steps.fetch-members.outputs.members }}"
        if [[ $MEMBERS =~ (^|[[:space:]])"$PR_OPENER"($|[[:space:]]) ]]; then
          echo "PR opener is a member of the organization."
          echo "{EXTERNAL}=false" >> $GITHUB_OUTPUT
        else
          gh issue edit "$NUMBER" --add-label "$LABELS"
          echo "{EXTERNAL}=true" >> $GITHUB_OUTPUT
        fi
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: contributor
  label-pr:
    runs-on: ubuntu-latest
    if: ${{ needs.check-external.outputs.EXTERNAL == 'true' }}
    needs: [check-external] # Ensure this job waits for `check-external` to complete
    steps:
    - uses: actions/checkout@v4
    - name: Label PR
      uses: actions/labeler@v5
